# Gaussian Elimination Method

Gaussian Elimination is a method for solving systems of linear equations by transforming the augmented matrix to row echelon form, then using back substitution.

**Process:**
1. **Forward Elimination:** Convert to upper triangular form
2. **Back Substitution:** Solve from bottom to top

**Example System:**
- 2x + y - z = 8
- -3x - y + 2z = -11  
- -2x + y + 2z = -3

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def gauss_elimination(A, b):
    n = len(b)
    Ab = np.hstack([A.astype(float), b.reshape(-1,1).astype(float)])
    steps = []  # to store solutions after each forward elimination
    
    print("Initial Augmented Matrix [A|b]:")
    print(Ab)
    print()
    
    # Forward Elimination
    for i in range(n):
        pivot = Ab[i][i]
        if pivot == 0:
            raise ValueError("Zero pivot encountered!")
        Ab[i] = Ab[i] / pivot
        
        for j in range(i+1, n):
            factor = Ab[j][i]
            Ab[j] = Ab[j] - factor * Ab[i]
        
        # Store current estimated solutions (upper triangular)
        x_est = np.zeros(n)
        for k in range(i+1):
            x_est[k] = Ab[k, -1]
        steps.append(x_est.copy())
        
        print(f"After eliminating column {i+1}:")
        print(Ab)
        print()
    
    # Back Substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = Ab[i,-1] - np.sum(Ab[i, i+1:n]*x[i+1:n])
    
    return x, steps

In [3]:
# Example system
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]], dtype=float)
b = np.array([8, -11, -3], dtype=float)

solution, steps = gauss_elimination(A, b)
print("Solution vector x =", solution)

Solving the system:
2x + y - z = 8
-3x - y + 2z = -11
-2x + y + 2z = -3

Initial Augmented Matrix [A|b]:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Swapped row 0 with row 1
After eliminating column 1:
[[ 1.          0.33333333 -0.66666667  3.66666667]
 [ 0.          0.33333333  0.33333333  0.66666667]
 [ 0.          1.66666667  0.66666667  4.33333333]]

Swapped row 1 with row 2
After eliminating column 2:
[[ 1.          0.33333333 -0.66666667  3.66666667]
 [ 0.          1.          0.4         2.6       ]
 [ 0.          0.          0.2        -0.2       ]]

After eliminating column 3:
[[ 1.          0.33333333 -0.66666667  3.66666667]
 [ 0.          1.          0.4         2.6       ]
 [ 0.          0.          1.         -1.        ]]

Final Solution Vector:
x = [ 2.  3. -1.]


In [4]:
# Plotting
variables = ['x', 'y', 'z']
for i, step in enumerate(steps):
    plt.bar([v + f" (step {i+1})" for v in variables], step, alpha=0.7, label=f'Step {i+1}')

plt.ylabel("Value")
plt.title("Gauss Elimination: Forward Elimination Steps")
plt.grid(axis='y')
plt.legend()
plt.show()


VERIFICATION:
Original matrix A:
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Original vector b:
[  8. -11.  -3.]

Solution x:
[ 2.  3. -1.]

Verification A @ x:
[  8. -11.  -3.]

Difference (should be close to zero):
[0. 0. 0.]

Solution is correct: True
✅ Gaussian Elimination successful!

Final Answer:
x = 2.000000
y = 3.000000
z = -1.000000
