# 🧠 Ultimate Guide to NumPy (A to Z)

> 🔬 **NumPy (Numerical Python)** is a high-performance library for numerical and scientific computing in Python. It's the foundation for many other libraries like Pandas, SciPy, Scikit-learn, TensorFlow, and more.

---

## 🛠️ Why Use NumPy?

| Feature                     | Explanation                                                        | Use Case                         |
| --------------------------- | ------------------------------------------------------------------ | -------------------------------- |
| 🚀 Speed                    | Much faster than Python lists due to C-based implementation        | Data processing, ML pipelines    |
| 🧮 Multi-dimensional Arrays | Supports n-dimensional arrays with efficient operations            | Matrix algebra, image processing |
| 🧰 Rich Functions           | Built-in ufuncs (universal functions), linear algebra, stats, etc. | Math-heavy applications          |
| 📊 Interoperability         | Works with other libraries like Pandas, Matplotlib, TensorFlow     | Ecosystem compatibility          |

---

## ⚙️ Installation & Setup

```bash
pip install numpy
```

```python
import numpy as np
```

---

## 🔤 NumPy Arrays

### ▶️ Creating Arrays

```python
np.array([1, 2, 3])                # From Python list
np.zeros((2, 3))                   # Array of zeros
np.ones((3, 2))                    # Array of ones
np.arange(0, 10, 2)                # Even numbers till 10
np.linspace(0, 1, 5)               # 5 equally spaced values from 0 to 1
```

📌 **Use Case:** Initializing matrices or arrays in simulations, computations, or empty data templates.

---

## 🔄 Reshaping, Indexing, and Slicing

```python
arr = np.arange(12)
arr = arr.reshape((3, 4))  # 3x4 matrix
arr[0, 1]       # Access 1st row, 2nd column
arr[:, 2]       # Access all rows, 3rd column
arr[1:3, :]     # Slice rows 2 to 3
```

📌 **Use Case:** Data reshaping in ML (e.g., flattening images to 1D arrays).

---

## 🔬 Array Properties

```python
arr.shape     # (3, 4)
arr.ndim      # 2
arr.dtype     # int64
arr.size      # Total number of elements
```

📌 **Use Case:** Validating input dimensions and structure.

---

## ➗ Arithmetic Operations & Broadcasting

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)      # [5 7 9]
print(a * 2)      # [2 4 6]
print(np.sin(a))  # [0.84 0.91 0.14]
```

📌 **Use Case:** Element-wise operations, scaling, transformations.

---

## 🔄 Broadcasting

```python
m = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 0, 1])
print(m + v)
# [[2 2 4]
#  [5 5 7]]
```

📌 **Use Case:** Efficient addition without writing explicit loops.

---

## 📏 Aggregation Functions

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.sum()           # 21
arr.mean(axis=0)    # [2.5 3.5 4.5]
arr.max(axis=1)     # [3 6]
```

📌 **Use Case:** Statistical summaries for rows, columns, or full data.

---

## 🔍 Searching, Sorting, Filtering

```python
arr = np.array([10, 3, 7, 1])
np.sort(arr)         # [1, 3, 7, 10]
np.where(arr > 5)    # Indices where condition is True
np.argmax(arr)       # Index of max value
```

📌 **Use Case:** Conditional filtering, feature ranking.

---

## 🧮 Linear Algebra

```python
mat = np.array([[1, 2], [3, 4]])
np.dot(mat, mat)               # Matrix multiplication
np.linalg.inv(mat)            # Inverse
np.linalg.det(mat)            # Determinant
np.linalg.eig(mat)            # Eigenvalues & vectors
```

📌 **Use Case:** Solving systems of equations, PCA, ML algorithms.

---

## 🎲 Random Number Generation

```python
np.random.seed(42)
np.random.rand(3)             # Uniform [0, 1)
np.random.randint(1, 10, 5)   # Random integers
np.random.normal(0, 1, 1000)  # Normal distribution
```

📌 **Use Case:** Simulations, synthetic data generation, initializing weights in ML.

---

## 📁 File I/O

```python
np.savetxt("data.csv", arr, delimiter=",")
arr2 = np.loadtxt("data.csv", delimiter=",")
```

📌 **Use Case:** Saving and loading datasets efficiently.

---

## 🔤 Data Types and Casting

```python
arr = np.array([1.0, 2.5, 3.8])
arr.astype(int)       # Convert to integers
```

📌 **Use Case:** Matching input/output formats, memory efficiency.

---

## 📚 Summary Table of Key Functions

| Category        | Function Examples                              | Description                      |
| --------------- | ---------------------------------------------- | -------------------------------- |
| Creation        | `array`, `zeros`, `ones`, `arange`, `linspace` | Create different types of arrays |
| Reshaping       | `reshape`, `ravel`, `flatten`                  | Change array shape               |
| Math Operations | `+`, `-`, `*`, `/`, `sin`, `log`, `exp`        | Element-wise ops                 |
| Aggregation     | `sum`, `mean`, `std`, `min`, `max`             | Reduce data                      |
| Linear Algebra  | `dot`, `inv`, `eig`, `det`                     | Matrix math                      |
| Random          | `rand`, `randn`, `randint`                     | Generate random numbers          |
| Searching       | `where`, `argmax`, `argmin`, `nonzero`         | Conditions & index ops           |
| File I/O        | `loadtxt`, `savetxt`, `save`, `load`           | File operations                  |

---

## ✅ Final Tips for Mastery

* ✅ Practice slicing and broadcasting frequently.
* ✅ Memorize key aggregation and matrix ops.
* ✅ Explore real datasets and visualize them using `matplotlib`.
* ✅ Use `.shape` and `.dtype` to debug shape errors.
* ✅ Read NumPy docs: [https://numpy.org/doc/stable/](https://numpy.org/doc/stable/)

---

Happy Learning! 🎉


In [1]:
import numpy as np

In [7]:

np.random.seed(42)  # Sets the random seed for reproducibility
np.random.rand(3, 3)  # Generates a 3x3 array of random floats in the half-open interval [0.0, 1.0)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [10]:

#  np.random.randint(1, 10, (2, 3))  # Generates a 2x3 array with random integers between 1 and 10 (exclusive of 10)
np.random.randn(2, 3)  # Generates a 2x3 array with random floats from a standard normal distribution (mean=0, std=1)
np.random.choice([1, 2, 3, 4, 5], size=(2, 3))  # Generates a 2x3 array with random choices from the list [1, 2, 3, 4, 5]
# np.random.seed(42)  # Sets the random seed for reproducibility  

array([[3, 4, 4],
       [1, 3, 5]])