# Gauss–Jordan Elimination Method
This notebook demonstrates solving a system of linear equations using the Gauss–Jordan method in Python.

In [1]:
import numpy as np

def print_matrix_step(matrix, step_desc):
    """Helper function to print matrix at each step"""
    print(f"\n{step_desc}:")
    print(matrix)

def gauss_jordan(a, b):
    # Create augmented matrix [A|B]
    aug_matrix = np.concatenate((a, b), axis=1)
    rows, cols = aug_matrix.shape
    print_matrix_step(aug_matrix, "Initial Augmented Matrix")

    # Perform Gauss–Jordan elimination
    for i in range(rows):
        # Step 1: Make pivot element = 1
        pivot = aug_matrix[i, i]
        if pivot == 0:
            raise ValueError("Zero pivot encountered!")
        aug_matrix[i] = aug_matrix[i] / pivot
        print_matrix_step(aug_matrix, f"Make pivot in row {i+1} = 1")

        # Step 2: Make other elements in column i = 0
        for j in range(rows):
            if i != j:
                factor = aug_matrix[j, i]
                aug_matrix[j] = aug_matrix[j] - factor * aug_matrix[i]
        print_matrix_step(aug_matrix, f"Eliminate other entries in column {i+1}")

    # Last column contains the solution
    solution = aug_matrix[:, -1]
    return solution

# Example system of equations:
# 2x + y - z = 8
# -3x - y + 2z = -11
# -2x + y + 2z = -3

A = np.array([[2.0, 1.0, -1.0],
              [-3.0, -1.0, 2.0],
              [-2.0, 1.0, 2.0]])
B = np.array([[8.0],
              [-11.0],
              [-3.0]])

# Solve using Gauss–Jordan
solution = gauss_jordan(A, B)

# Final solution
print("\nFinal Solution:")
for i, val in enumerate(solution, start=1):
    print(f"x{i} = {val}")


Initial Augmented Matrix:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Make pivot in row 1 = 1:
[[  1.    0.5  -0.5   4. ]
 [ -3.   -1.    2.  -11. ]
 [ -2.    1.    2.   -3. ]]

Eliminate other entries in column 1:
[[ 1.   0.5 -0.5  4. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Make pivot in row 2 = 1:
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [ 0.   2.   1.   5. ]]

Eliminate other entries in column 2:
[[ 1.  0. -1.  3.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -1.  1.]]

Make pivot in row 3 = 1:
[[ 1.  0. -1.  3.]
 [ 0.  1.  1.  2.]
 [-0. -0.  1. -1.]]

Eliminate other entries in column 3:
[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [-0. -0.  1. -1.]]

Final Solution:
x1 = 2.0
x2 = 3.0
x3 = -1.0


In [6]:
import numpy as np

print("SOLVING ALL SYSTEMS OF EQUATIONS (robust)")
print("=" * 60)

def solve_safe(A, b, name="System"):
    try:
        sol = np.linalg.solve(A, b)
        print(f"{name} solution: " + ", ".join(f"{v:.6f}" for v in sol))
        return sol, None
    except np.linalg.LinAlgError as e:
        print(f"{name} - LinAlgError: {e}")
        sol, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
        print(f"{name} - least-squares fallback (may not be unique): " + ", ".join(f"{v:.6f}" for v in sol))
        return sol, (residuals, rank, s)

# Problem definitions (as in your script, with corrected spring matrix)
A1 = np.array([[1, 3, 2], [2, 1, 7], [2, 1, 2]], dtype=float)
b1 = np.array([2, -1, 7], dtype=float)

A2 = np.array([[2, 4, -6], [1, 2, 3], [3, -4, 4]], dtype=float)
b2 = np.array([38, 7, -19], dtype=float)

g = 9.81; m1, m2, m3 = 2.0, 3.0, 2.5; k = 10.0
A3 = np.array([[2*k, -k,   0.0],
               [-k,  2*k, -k  ],
               [0.0, -k,   k  ]], dtype=float)
b3 = np.array([m1*g, m2*g, m3*g], dtype=float)

A4 = np.array([[2, -2, 3], [1, 2, -1], [3, -1, 2]], dtype=float)
b4 = np.array([2, 3, 1], dtype=float)

# Solve
sol1, _ = solve_safe(A1,b1,"System 1")
sol2, _ = solve_safe(A2,b2,"System 2")
sol3, _ = solve_safe(A3,b3,"Spring system")
sol4, _ = solve_safe(A4,b4,"System 4")


SOLVING ALL SYSTEMS OF EQUATIONS (robust)
System 1 solution: 5.080000, 0.040000, -1.600000
System 2 solution: 3.000000, 5.000000, -2.000000
Spring system solution: 7.357500, 12.753000, 15.205500
System 4 solution: -1.000000, 4.000000, 4.000000
