# Gauss–Jordan Elimination Method
This notebook demonstrates solving a system of linear equations using the Gauss–Jordan method in Python.

In [1]:
import numpy as np

def print_matrix_step(matrix, step_desc):
    """Helper function to print matrix at each step"""
    print(f"\n{step_desc}:")
    print(matrix)

def gauss_jordan(a, b):
    # Create augmented matrix [A|B]
    aug_matrix = np.concatenate((a, b), axis=1)
    rows, cols = aug_matrix.shape
    print_matrix_step(aug_matrix, "Initial Augmented Matrix")

    # Perform Gauss–Jordan elimination
    for i in range(rows):
        # Step 1: Make pivot element = 1
        pivot = aug_matrix[i, i]
        if pivot == 0:
            raise ValueError("Zero pivot encountered!")
        aug_matrix[i] = aug_matrix[i] / pivot
        print_matrix_step(aug_matrix, f"Make pivot in row {i+1} = 1")

        # Step 2: Make other elements in column i = 0
        for j in range(rows):
            if i != j:
                factor = aug_matrix[j, i]
                aug_matrix[j] = aug_matrix[j] - factor * aug_matrix[i]
        print_matrix_step(aug_matrix, f"Eliminate other entries in column {i+1}")

    # Last column contains the solution
    solution = aug_matrix[:, -1]
    return solution

# Example system of equations:
# 2x + y - z = 8
# -3x - y + 2z = -11
# -2x + y + 2z = -3

A = np.array([[2.0, 1.0, -1.0],
              [-3.0, -1.0, 2.0],
              [-2.0, 1.0, 2.0]])
B = np.array([[8.0],
              [-11.0],
              [-3.0]])

# Solve using Gauss–Jordan
solution = gauss_jordan(A, B)

# Final solution
print("\nFinal Solution:")
for i, val in enumerate(solution, start=1):
    print(f"x{i} = {val}")


Initial Augmented Matrix:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Make pivot in row 1 = 1:
[[  1.    0.5  -0.5   4. ]
 [ -3.   -1.    2.  -11. ]
 [ -2.    1.    2.   -3. ]]

Eliminate other entries in column 1:
[[ 1.   0.5 -0.5  4. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   2.   1.   5. ]]

Make pivot in row 2 = 1:
[[ 1.   0.5 -0.5  4. ]
 [ 0.   1.   1.   2. ]
 [ 0.   2.   1.   5. ]]

Eliminate other entries in column 2:
[[ 1.  0. -1.  3.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -1.  1.]]

Make pivot in row 3 = 1:
[[ 1.  0. -1.  3.]
 [ 0.  1.  1.  2.]
 [-0. -0.  1. -1.]]

Eliminate other entries in column 3:
[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [-0. -0.  1. -1.]]

Final Solution:
x1 = 2.0
x2 = 3.0
x3 = -1.0
